### ISSUE TITLE
Oops in __htab_map_lookup_elem() with test_verifier

### ISSUE THREAD

**Issue by mpe** [linuxppc/issues#262] opened 2019-07-30 06:53 UTC
With `bpf_jit_harden > 0` the bpf `test_verifier` test oopses:

```
# /home/michael/test_verifier 
#0/u invalid and of negative number OK
#0/p invalid and of negative number OK
#1/u invalid range check OK
#1/p invalid range check OK
#2/u valid map access into an array with a constant OK
[ 1004.972680] BUG: Unable to handle kernel data access at 0xffffffff3cdf5c14
[ 1004.972694] Faulting instruction address: 0xc0000000002a5394
[ 1004.972702] Oops: Kernel access of bad area, sig: 11 [#1]
[ 1004.972709] LE PAGE_SIZE=64K MMU=Hash SMP NR_CPUS=2048 NUMA PowerNV
[ 1004.972716] Modules linked in: iptable_mangle xt_MASQUERADE iptable_nat nf_nat xt_conntrack nf_conntrack nf_defrag_ipv4 ipt_REJECT nf_reject_ipv4 xt_tcpudp tun bridge stp llc iptable_filter fuse kvm_hv kvm squashfs binfmt_misc mlx4_ib ib_uverbs dm_multipath scsi_dh_rdac ib_core scsi_dh_alua mlx4_en lpfc bnx2x mlx4_core crc_t10dif crct10dif_generic mdio crct10dif_common vmx_crypto gf128mul crc32c_vpmsum powernv_rng rng_core leds_powernv powernv_op_panel led_class ip_tables x_tables autofs4
[ 1004.972779] CPU: 39 PID: 9278 Comm: test_verifier Not tainted 5.3.0-rc2-gcc-8.2.0-00011-g2a11c76e5301 #494
[ 1004.972787] NIP:  c0000000002a5394 LR: c0080000089addb4 CTR: c0080000089add24
[ 1004.972796] REGS: c00000075e597860 TRAP: 0380   Not tainted  (5.3.0-rc2-gcc-8.2.0-00011-g2a11c76e5301)
[ 1004.972803] MSR:  9000000000009033 <SF,HV,EE,ME,IR,DR,RI,LE>  CR: 24022842  XER: 20000000
[ 1004.972815] CFAR: c0080000089addb0 IRQMASK: 0 
[ 1004.972815] GPR00: c0080000089addb4 c00000075e597af0 c000000001617300 ffffffff3cdf5c00 
[ 1004.972815] GPR04: c00000075e597b18 ffffffffffffffff 0000000001f40050 001b177afff819f8 
[ 1004.972815] GPR08: 0000000000000000 ffffffff871ea82f 0000000000000000 c000000000ad7c80 
[ 1004.972815] GPR12: c0000000002a5380 c0000007fffdf200 0000000000000000 0000000000000000 
[ 1004.972815] GPR16: 0000000000000000 0000000000000000 0000000000000000 0000000000000001 
[ 1004.972815] GPR20: c00000075e597c50 c0000000011c4c28 c00000075e597c4c c0000000011c4c20 
[ 1004.972815] GPR24: 0000000000000001 0000000000000000 c008000008960038 c0000007e6c1e400 
[ 1004.972815] GPR28: 000000e9fd1ed874 0000000000000001 c008000008960000 c00000075e597b20 
[ 1004.972878] NIP [c0000000002a5394] __htab_map_lookup_elem+0x14/0x270
[ 1004.972886] LR [c0080000089addb4] 0xc0080000089addb4
[ 1004.972891] Call Trace:
[ 1004.972896] [c00000075e597af0] [0000000000080002] 0x80002 (unreliable)
[ 1004.972905] [c00000075e597b60] [c000000000b8e95c] bpf_test_run+0x16c/0x380
[ 1004.972913] [c00000075e597c20] [c000000000b8f168] bpf_prog_test_run_skb+0x358/0x650
[ 1004.972922] [c00000075e597cc0] [c00000000028ed2c] sys_bpf+0xf6c/0x21e0
[ 1004.972931] [c00000075e597e20] [c00000000000badc] system_call+0x5c/0x70
[ 1004.972937] Instruction dump:
[ 1004.972942] eb81ffe0 eba1ffe8 ebc1fff0 ebe1fff8 7c0803a6 4e800020 60000000 3c4c0137 
[ 1004.972952] 38421f80 7c0802a6 60000000 fbe1fff8 <80c30014> 80e30394 7c852378 7cac2b78 
[ 1004.972964] ---[ end trace c76be29f2e157f66 ]---
```

**Comment by rnav** [comment] 2019-08-13 17:39
This is a duplicate of #261

**Closed** 2019-08-14 07:19 UTC
Labels: bug
