### ISSUE TITLE
recordmcount failures building with binutils 2.37

### ISSUE THREAD

**Issue by chleroy** [linuxppc/issues#388] opened 2021-11-22 09:29 UTC
`ppc64_defconfig` build fails: 

```
  CC      kernel/kexec_file.o
Cannot find symbol for section 10: .text.unlikely.
kernel/kexec_file.o: failed
make[1]: *** [scripts/Makefile.build:287 : kernel/kexec_file.o] Erreur 1

```
With `CONFIG_FUNCTION_TRACER` disabled it works

With V=1 we see the problems comes from recordmcount:

```
   if [ kernel/kexec_file.o != "scripts/mod/empty.o" ]; then ./scripts/recordmcount  "kernel/kexec_file.o"; fi;
Cannot find symbol for section 10: .text.unlikely.
kernel/kexec_file.o: failed

```

The problem seems to be known and linked to recent binutils https://www.spinics.net/lists/kexec/msg27392.html

Used crosstools:
- binutils-powerpc64-linux-gnu-2.37-3.fc35.x86_64
- gcc-powerpc64-linux-gnu-11.2.1-1.fc35.x86_64

**Comment by shenki** [comment] 2021-11-23 06:51
This was reported by Greg a while back too:

https://lore.kernel.org/all/YCfdfkoeh8i0baCj@kroah.com/

It looks similar to a report from a while back that resulted in this patch:

 https://lore.kernel.org/all/20210215162209.5e2a475b@gandalf.local.home/
 
Unrelated to the above, this is a fix that went into the binutils 2.37 branch after release:
 
 https://sourceware.org/git/?p=binutils-gdb.git;a=commit;h=b1d7b59622f9941e7fa72418b7a41f148d83155e
 
I tried to reproduce using Debian's binutils 2.37 (2.37-7) and gcc 11.2.0 (11.2.0-2), building v5.16-rc2, and the build succeeded. I also tried linking with binutils-2_37-164-g9d4007191ceb (HEAD of binutils-2_37-branch) and that worked too.

**Comment by chleroy** [comment] 2021-11-25 05:44
Proposed patch https://patchwork.ozlabs.org/project/linuxppc-dev/patch/cd0f6bdfdf1ee096fb2c07e7b38940921b8e9118.1637764848.git.christophe.leroy@csgroup.eu/

**Comment by chleroy** [comment] 2021-11-29 17:31
`objdump -x` shows that `.text.unlikely` section only has weak symbols, the problem is that  `recordmcount` drops/ignore weak symbols:

```
0000000000000000  w    F .text.unlikely	0000000000000038 .arch_kexec_apply_relocations_add
0000000000000038  w    F .text.unlikely	0000000000000038 .arch_kexec_apply_relocations
```

With GCC 10, we have an additional local symbol which has the name of the section:

```
0000000000000000 l    d  .text.unlikely	0000000000000000 .text.unlikely
0000000000000000  w    F .text.unlikely	0000000000000038 .arch_kexec_apply_relocations_add
0000000000000038  w    F .text.unlikely	0000000000000038 .arch_kexec_apply_relocations
```

**Comment by chleroy** [comment] 2021-11-30 14:48
With GCC 11 from kernel crosstools, which also has binutils 2.36.1, it works.
So the problem is likely dependent on binutils version and not of gcc.

**Comment by legoater** [comment] 2022-04-30 09:46
the buildroot `qemu_ppc64le_powernv8_defconfig` build reports the error. See https://gitlab.com/buildroot.org/buildroot/-/jobs/2387778079

**Comment by mpe** [comment] 2022-05-01 12:28
@rnav has posted a series that should fix it: https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=297434

**Comment by legoater** [comment] 2022-05-07 07:23
Hello @rnav, I see that these patches are now in the  "Handled  Elsewhere" state. Did another maintainer take them ?

**Comment by chleroy** [comment] 2022-05-07 07:56
@legoater, based on the comments I'd say 'not yet', but regardless these patches are to be handled through the ftrace tree.

**Comment by legoater** [comment] 2022-05-08 07:03
Thanks @chleroy. I will track the repo to cherry pick the patches, if possible.

**Comment by rnav** [comment] 2022-05-16 06:43
@legoater not sure about the 'handled elsewhere' part - this hasn't been solved upstream yet.

`objtool` now has a more appropriate fix for this, so moving to `objtool` will help in the longer term:
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/tools/objtool/elf.c?id=4abff6d48dbcea8200c7ea35ba70c242d128ebf3

Short term, I'm thinking it is simpler if we go with this workaround:
https://patchwork.ozlabs.org/project/linuxppc-dev/patch/20220425174128.11455-1-naveen.n.rao@linux.vnet.ibm.com/

@mpe there is precedence, so I'm hoping this isn't too controversial:
- https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/init/initramfs.c?id=55d5b7dd6451b58489ce384282ca5a4a289eb8d5
- https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/include/linux/elfcore.h?id=6e7b64b9dd6d96537d816ea07ec26b7dedd397b9

**Comment by legoater** [comment] 2022-05-16 07:32
@rnav I have downgraded binutils for now in buildroot : https://gitlab.com/legoater/buildroot/-/pipelines/539559209

**Comment by mpe** [comment] 2022-05-17 06:29
It's not really my change to merge, I was hoping we'd hear something from the kexec folks.

It would affect powerpc, parisc and arm64, all of which have KEXEC_FILE but don't implement those hooks.

I also don't see why removing the `pr_err()`s causes the compiler to put the code in `.text` rather than `.text.unlikely`, it seems like that might just be luck?

**Comment by rnav** [comment] 2022-05-17 08:05
I've replied to the patch.

Josh suggested it could be due to printk() being cold: http://lkml.kernel.org/r/20210214155147.3owdimqv2lyhu6by@treble
Incidentally, afaics, this seems to be the only place we are missing a section symbol resulting in `recordmcount` failing.

**Comment by mpe** [comment] 2022-05-17 10:33
Thanks for replying, that has at least kicked the discussion along.

I see several other places when building `allmodconfig` on Fedora 36:
```
Cannot find symbol for section 12: .text.perf_callchain_kernel.
kernel/events/callchain.o: failed
Cannot find symbol for section 52: .text.arch_show_interrupts.
kernel/irq/proc.o: failed
Cannot find symbol for section 61: .text.arch_prepare_bpf_trampoline.
kernel/bpf/trampoline.o: failed
Cannot find symbol for section 4: .text.arch_prepare_bpf_dispatcher.
kernel/bpf/dispatcher.o: failed
Cannot find symbol for section 141: .text.pci_adjust_legacy_attr.
drivers/pci/pci-sysfs.o: failed
Cannot find symbol for section 11: .text.arch_freq_prepare_all.
fs/proc/cpuinfo.o: failed
```

So the workaround would help, because the defconfig would build, but the issue is more pervasive.

**Comment by mpe** [comment] 2022-05-20 12:47
Andrew has picked up the workaround:
  https://git.kernel.org/pub/scm/linux/kernel/git/akpm/mm.git/log/?h=mm-nonmm-unstable

**Comment by mpe** [comment] 2022-08-01 04:32
The defconfig builds now since the work around is merged, but `allmodconfig` suffers from the same issue.

**Comment by chleroy** [comment] 2022-08-11 10:19
Ongoing work for using objtool --mcount instead of recordmcount : <https://patchwork.ozlabs.org/project/linuxppc-dev/list/?series=312955&state=*>

**Comment by rnav** [comment] 2022-08-18 13:39
With the above series, I tested `objtool` to confirm if it is able to handle object files without section symbols properly.

I reverted https://github.com/linuxppc/linux/commit/3e35142ef99fe6b4fe5d834ad43ee13cca10a2dc , generated a stock `kexec_file.o`:

```
$ objdump -t ./kernel/kexec_file.o | grep .text.unlikely
0000000000000000  w    F .text.unlikely	0000000000000040 0x60 arch_kexec_apply_relocations_add
0000000000000040  w    F .text.unlikely	0000000000000040 0x60 arch_kexec_apply_relocations
```

That shows that the symbol for the section `.text.unlikely` has been stripped from the symbol table.

```
$ ./scripts/recordmcount ./kernel/kexec_file.o
Cannot find symbol for section 6: .text.unlikely.
./kernel/kexec_file.o: failed
```

As expected, `recordmcount` complains about the lack of non-weak symbols in `.text.unlikely` section.

```
$ ./tools/objtool/objtool --mcount ./kernel/kexec_file.o
$ objdump -t ./kernel/kexec_file.o | grep .text.unlikely
0000000000000000 l    d  .text.unlikely	0000000000000000 .text.unlikely
0000000000000000  w    F .text.unlikely	0000000000000040 0x60 arch_kexec_apply_relocations_add
0000000000000040  w    F .text.unlikely	0000000000000040 0x60 arch_kexec_apply_relocations
```

`objtool` runs just fine on the file, and we can see that it has now added back `.text.unlikely` to the symbol table. It has also captured the mcount locations in that section:

```
$ objdump -r -j __mcount_loc ./kernel/kexec_file.o | grep .text.unlikely
0000000000000070 UNKNOWN           .text.unlikely+0x000000000000000c
0000000000000078 UNKNOWN           .text.unlikely+0x000000000000004c
```

**Comment by mpe** [comment] 2022-09-01 04:41
> The problem is amplified by CONFIG_LD_DEAD_CODE_DATA_ELIMINATION because there is only one function in each section.

Ah well spotted.

So I'm inclined to (temporarily) drop support for CONFIG_LD_DEAD_CODE_DATA_ELIMINATION from our Kconfig. None of our defconfigs enable it, and no distro enables it, so I don't think it will really be missed.

**Comment by chleroy** [comment] 2022-09-01 05:02
> 

Argh !  Fitting recent kernels on my oldest board is tricky, and CONFIG_LD_DEAD_CODE_DATA_ELIMINATION helps reducing vmlinux size by 10% so I'm using it actively.

But that's ppc32, so maybe disable it only on ppc64 ?
Or disable it only for binutils 2.37 ? Because I see problems neither with 2.38 nor 2.39.

**Comment by mpe** [comment] 2022-09-01 05:57
OK, good to know you're using it and it's working well.

If it's fixed in 2.38 then we need to work out when it was fixed, and then we could blacklist 2.37.

**Comment by legoater** [comment] 2022-09-24 08:54
Buildroot remove support for binutils 2.36 https://github.com/buildroot/buildroot/commit/d08639e6b9e5.

**Comment by chleroy** [comment] 2022-09-24 10:11
> Buildroot remove support for binutils 2.36 [buildroot/buildroot@d08639e6b9e5](https://github.com/buildroot/buildroot/commit/d08639e6b9e5).

Looks like they jumped from 2.36 to 2.38.

**Comment by legoater** [comment] 2022-09-24 13:50
yes. And the build with 2.38 looks fine now : https://gitlab.com/legoater/buildroot/-/pipelines/649659660

**Comment by chleroy** [comment] 2022-09-26 05:44
> what was the final fix ? I lost track.

Don't know exactly. They fixed something in binutils between 2.37 and 2.38.

**Comment by legoater** [comment] 2022-09-26 05:52
buildroot switched to 2.38 https://github.com/buildroot/buildroot/commit/e461c9adc82a889deb6e259ce811193cb8d00f36

**Comment by shenki** [comment] 2022-09-30 00:19
It was this patch I think: https://github.com/bminor/binutils-gdb/commit/c09c8b42021180eee9495bd50d8b35e683d3901b

I confirmed by applying it to binutils 2.37 and building the kernel.

**Comment by rnav** [comment] 2022-09-30 10:27
Good find! Glad that this is fixed in binutils.

**Comment by nickdesaulniers** [comment] 2022-10-26 18:39
That doesn't fix clang's integrated assembler!

**Comment by shenki** [comment] 2022-10-27 01:06
We should print a warning (or fail the build) when building with 2.27. Putting it in arch/powerpc/Makefile makes sense:

```
checkbin:
        @if test "x${CONFIG_LD_IS_LLD}" != "xy" -a \
                "x$(call ld-ifversion, -le, 22400, y)" = "xy" ; then \
                echo -n '*** binutils 2.24 miscompiles weak symbols ' ; \
                echo 'in some circumstances.' ; \
                echo    '*** binutils 2.23 do not define the TOC symbol ' ; \
                echo -n '*** Please use a different binutils version.' ; \
                false ; \
```

**Comment by shenki** [comment] 2022-10-27 01:06
> That doesn't fix clang's integrated assembler!

This issue is about binutils, do you have a failure with clang too? Perhaps open a new bug for that?

**Comment by rnav** [comment] 2022-10-28 07:56
> > That doesn't fix clang's integrated assembler!
> 
> This issue is about binutils, do you have a failure with clang too? Perhaps open a new bug for that?

I think that is being tracked here: https://github.com/ClangBuiltLinux/linux/issues/981

I like the patch to fail the build for binutils v2.27 if `CONFIG_FUNCTION_TRACER` is enabled, especially for -stable. Patches enabling use of `objtool` for recording mcount locations on powerpc should help fix these issues for clang's integrated assembler eventually.

**Comment by rnav** [comment] 2024-02-16 10:16
Patch to fail build for binutils v2.27 is upstream: [linuxppc/linux commit](https://github.com/linuxppc/linux/commit/25ea739ea1d4d3de41acc4f4eb2d1a97eee0eb75) 

We also have objtool support enabled to cover clang, so I think we are good here.

**Comment by mpe** [comment] 2024-02-16 11:01
Thanks everyone :vulcan_salute:

**Closed by mpe** 2024-02-16 11:01 UTC
Labels: in-progress, bug
